#pragma config(StandardModel, "GTT Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	startMotor(port2,100);//start the motor
	wait(2);//wait for 2 seconds
	stopMotor(port2);//stop the motor


}
