#pragma config(Sensor, in1,    light,          sensorLineFollower)
#pragma config(Sensor, dgtl11, BUMP,           sensorTouch)
#pragma config(Sensor, dgtl12, bump,           sensorTouch)
#pragma config(Motor,  port1,           Cool,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	repeat(forever){
	if (SensorValue(in1) < 150)
		startMotor(port1,-50);
	wait(1);
	stopMotor(port1);
	waitInMilliseconds(1);
	startMotor(port1,50);
	wait(1);
	stopMotor(port1);

}

}
