#pragma config(Sensor, dgtl1,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl2,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl9,  red,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, orange,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, green,          sensorLEDtoVCC)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightMotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{repeat(forever)
{
	untilBump(dgtl1);
	startMotor(port9,15);
	untilBump(dgtl2);
	stopMotor(port9);
}
}
