#pragma config(Sensor, dgtl1,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl2,  limitswitch,    sensorTouch)
#pragma config(Sensor, dgtl9,  green,          sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, yellow,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, red,            sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main ()
{repeat(forever)
	{
		turnLEDOff(dgtl9);
		turnLEDOff(dgtl10);
		turnLEDOff(dgtl11);
		turnLEDOn(dgtl11);
		wait(3);
		turnLEDOff(dgtl11);
		waitInMilliseconds(500);
		turnLEDOn(dgtl10);
		wait(3);
		turnLEDOff(dgtl10);
		waitInMilliseconds(500);
		turnLEDOn(dgtl9);
		wait(3);
		turnLEDOff(dgtl9);

		untilBump(dgtl1);
		turnLEDOn(dgtl11);
		wait(10);
		turnLEDOff(dgtl11);


	}
}
