#pragma config(StandardModel, "GTT Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	repeat(forever) {
		if(SensorValue(dgtl2)== 1) {
			startMotor (port3,75);
			startMotor (port2,-75);
		}
		if(SensorValue(dgtl1)== 1) {
			stopMotor(port2);
			stopMotor(port3);
		}
	}
}
