#pragma config(StandardModel, "GTT Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(true) {
		if (SensorValue(dgtl2) == 1) {
			startMotor(port2,69);
			startMotor(port3,69);
			wait(2);
			stopMotor(port2);
			stopMotor(port3);
  	}
	}
}
