#pragma config(StandardModel, "GTT Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	startMotor(port2,100);
	startMotor(port3,-100);
	wait(2);
	untilBump(dgtl1); {
		stopMotor(port2);
		stopMotor(port3);
		wait(0.5);
		startMotor(port2,-100);
		startMotor(port3,100);
		wait(1);
		stopMotor(port2);
		stopMotor(port3);
		wait(0.5);
		startMotor(port3,127);
		startMotor(port2,80);
		wait(9.89);
		stopMotor(port2);
		stopMotor(port3);
	}
}
