#pragma config(StandardModel, "GTT Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{repeat(forever){
	if(SensorValue[in1] >= 2400){
		turnLEDOn(dgtl12);
		startMotor(port2,-127);
		startMotor(port3,127);
	}
	else{
		turnLEDOff(dgtl12);
		stopMotor(port2);
		stopMotor(port3);
	}
}


}
