#pragma config(Sensor, in1,    lineFollower,   sensorNone)
#pragma config(Sensor, in2,    potentiometer,  sensorNone)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorNone)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorNone)
#pragma config(Sensor, dgtl10, LED,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, LED,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	turnLEDOn(dgtl10);
	startMotor(port2,120);
	startMotor(port3,120);
	wait(2);
	stopMotor(port2);
	stopMotor(port3);
	waitInMilliseconds(500);
	startMotor(port2,80);
	startMotor(port3,-80);
	wait(6.1);
	stopMotor(port2);
	stopMotor(port3);
	wait(2);
	startMotor(port2,-127);
	startMotor(port3,-127);
	wait(6.7);
	startMotor(port2,-120);
	startMotor(port3,120);
	wait(4.9);
	stopMotor(port2);
	stopMotor(port3);
	wait(4);
	startMotor(port2,-120);
	startMotor(port3,-120);
	wait(4);
	startMotor(port2,100);
	startMotor(port3,-100);
	wait(5.6);
	stopMotor(port2);
	stopMotor(port3);
	turnLEDOff(dgtl10);
	wait(5);
	turnLEDOn(dgtl11);
	waitInMilliseconds(1);
	startMotor(port2,-60);
	startMotor(port3,60);
	wait(7);
	stopMotor(port2);
	stopMotor(port3);
	wait(2);
	startMotor(port2,60);
	startMotor(port3,60);
	wait(4);
	stopMotor(port2);
	stopMotor(port3);
	startMotor(port2,-120);
	startMotor(port3,120);
	wait(5.8);
	stopMotor(port2);
	stopMotor(port3);
	waitInMilliseconds(1);
	startMotor(port2,-127);
	startMotor(port3,-127);
	wait(7);
	stopMotor(port2);
	stopMotor(port3);
	waitInMilliseconds(1);
	startMotor(port2,-120);
	startMotor(port3,120);
	wait(5);
	stopMotor(port2);
	stopMotor(port3);
	waitInMilliseconds(1);
	startMotor(port2,120);
	startMotor(port3,120);
	wait(2);
	stopMotor(port2);
	stopMotor(port3);
}
