#pragma config(StandardModel, "GTT Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while(true) {
		//Bumpswitch Start
		waitUntil(SensorValue(dgtl2) == 1);
		startMotor(port2, -50);
		startMotor(port3, 50);
		delay(10);

		//BumpSwitch End
		waitUntil(SensorValue(dgtl2) == 1);
		stopMotor(port2);
		stopMotor(port3);
		delay(10);
	}
}
