#pragma config(StandardModel, "GTT Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	repeat(forever) {
		while(true) {
			if (SensorValue(dgtl2) == 1) {
				startMotor(port2, 50);
				startMotor(port3, 50);
			}
			if (SensorValue(dgtl1) == 1) {
				stopMotor(port2);
				stopMotor(port3);
			}
		}
	}
}
