#pragma config(StandardModel, "GTT Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	//Start Right
	startMotor(port2, 100);
	//Wait
	wait(2);
	//Stop
	stopMotor(port2);
}
