#pragma config(StandardModel, "GTT Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	//Start Right
	startMotor(port2, -50);
	startMotor(port3, -50);
	//Wait
	wait(3);
	//Stop
	stopMotor(port2);
	stopMotor(port3);
}
