#pragma config(Sensor, in4,    linefollow,     sensorLineFollower)
#pragma config(Sensor, dgtl1,  limit,          sensorTouch)
#pragma config(Sensor, dgtl2,  bump,           sensorTouch)
#pragma config(Sensor, dgtl4,  green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           claw,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           leftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
repeat(forever);
turnLEDOn(dgtl4);

untilBump(dgtl2);
stopMotor(port2);
stopMotor(port9);
wait(3);
startMotor(port2,-100);
startMotor(port9,-100);

untilBump(dgtl1);
stopMotor(port2);
stopMotor(port9);
wait(3);
startMotor(port2,100);
startMotor(port9,100);

}
