#pragma config(Sensor, in1,    Lol,            sensorLineFollower)
#pragma config(Sensor, dgtl11, R,              sensorTouch)
#pragma config(Sensor, dgtl12, L,              sensorTouch)
#pragma config(Motor,  port1,           movingthing,   tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           cuttingthing,  tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	repeat(forever){
		if(SensorValue[dgtl12] == 1){   // right
			startMotor(port1,127);
			waitUntil(SensorValue[dgtl12] == 0);
			stopMotor(port1);
		}

		if(SensorValue[dgtl11] == 1){   // left
			startMotor(port1,-30);
			waitUntil(SensorValue[dgtl11] == 0);
			stopMotor(port1);
		}

		if(SensorValue(in1) < 250){
			startMotor(port2,127);
			startMotor(port1,50);
			wait(2);
			stopMotor(port2);
			stopMotor(port1);

		}
	}
}
