#pragma config(Sensor, in1,    line,           sensorLineFollower)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{startMotor(port1,50);
	wait(1);
	stopMotor(port1);



}
