#pragma config(StandardModel, "GTT Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	startMotor(port2);
	backward(50);
	startMotor(port3);
	backward(50);
	wait(3);
	stopMotor(port2);
	stopMotor(port3);






}
