#pragma config(StandardModel, "GTT Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	repeat(forever) {
		if (SensorValue(dgtl2) == 1) {
			startMotor(port2,100);
			if (SensorValue(dgtl2) == 0)
				stopMotor(port2);
		}
	}
}
