#pragma config(Sensor, dgtl8,  Green,          sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, yellow,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, ,               sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, red,            sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  repeat(forever)
	turnLEDOn(dgtl8);
	wait(1);
	turnLEDOff(dgtl8);
	waitInMilliseconds(1);
	turnLEDOn(dgtl10);
	wait(1);
	turnLEDOff(dgtl10);
	waitInMilliseconds(1);
	turnLEDOn(dgtl12);
	wait(1);
	turnLEDOff(dgtl12);

}
