#pragma config(StandardModel, "GTT Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{
	repeat(forever){

		if(SensorValue[dgtl1]==1) {
			startMotor(port2, 50);
			startMotor(port3, -50);
			wait(1);
			stopMotor(port2);
			stopMotor(port3);
			wait(1);
			startMotor(port2, 127);
			startMotor(port3, 127);
			waitInMilliseconds(9470);
			stopMotor(port2);
			stopMotor(port3);
		}
	}
}
