#pragma config(StandardModel, "GTT Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	startMotor(port2,-50);//start the right motor
	startMotor(port3,50);//start the left motor
	wait(3);//wait 3 seconds
	stopMotor(port2);//stop the right motor
	stopMotor(port3);//stop the left motor



}
