#pragma config(StandardModel, "GTT Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	repeat(forever){
		if(SensorValue[dgtl2] == 1){// when the bumper switch is pressed, do this
			startMotor(port2, 100);//start the right motor
			startMotor(port3,-100);//start the left motor

			if(SensorValue[dgtl2] == 1){//when the bumper switch is pressed again, do this
				stopMotor(port2);//stop the right motor
				stopMotor(port3);//stop the left motor

			}
		}
	}
}
