#pragma config(StandardModel, "GTT Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	repeat(forever) {
		if (SensorValue[dgtl2] == 1){//when the bumper sw
			startMotor(port2,63);
			startMotor(port3,-63);
}
			if (SensorValue[dgtl1] == 1){
				stopMotor(port2);
				stopMotor(port3);
}
	}
}
