#pragma config(StandardModel, "GTT Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
//	repeat(forever){
//if (SensorValue [dgtl2] == 1){
//startMotor(port2, 127);
startMotor(port3, 10);
waitInMilliseconds(4450);
//stopMotor(port2);
stopMotor(port3);
		}
//	}
//}
