#pragma config(Sensor, dgtl10, yellow,         sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()

{
startmotor(port2, 30):
wait(5):
stopMotor(port2):
}
