#pragma config(StandardModel, "GTT Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	untilBump(dgtl2);//wait until bump on bump switch to start both motors
	startMotor (port1,-50);//start this one
	startMotor (port10, 50);//start this one
	waitInMilliseconds (100);//wait 100 millisec
	untilBump(dgtl2);//wait until bump on bump switch to stop both motors
	stopMotor(port1);//stop this motor
	stopMotor (port10);//stop this motor
}
