#pragma config(StandardModel, "GTT Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
startMotor(port1,50);//start this motor
startMotor(port10,-50);//start this also
wait(3);//wait for 3 seconds
stopMotor(port1);//stop this motor
stopMotor(port10);//stop this also
}
