#pragma config(StandardModel, "GTT Testbed")
#pragma config(RenamedStdModelMotor, port1, Motorclaw)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{startMotor (port1,-20);
	wait(4);
	stopMotor(port1);
	}
