#pragma config(StandardModel, "GTT Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{untilBump (dgtl2);//wait for bump on bump switch to start task
startMotor (port1,63.5);//start motor 1
startMotor (port10,-63.5);//start motor 10
wait(2);//wait for 2 sec
stopMotor(port1);//stop this motor
stopMotor(port10);//stop dat motor
}
