#pragma config(StandardModel, "GTT Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	startMotor(port1,-127);
	startMotor(port10,127);
	untilBump(dgtl1);
	stopMotor(port1);
	stopMotor(port10);
	startMotor(port1,127);
	startMotor(port10,-127);
	wait(2);
	stopMotor(port1);
	stopMotor(port10);
	startMotor(port1,127);
	startMotor(port10,127);
	wait(6);
	stopMotor(port1);
	stopMotor(port10);
	}
