#pragma config(StandardModel, "GTT Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	repeat(forever){//repeat the code forever
	untilBump(dgtl2);//wait until bump on bump switch
	startMotor (port1,-50); //start this motor
	startMotor (port10, 50);//start this motor
	waitInMilliseconds (100);// wait for 100 milliseconds
	untilBump(dgtl1); //wait until bump on limit switch
	stopMotor(port1); //stop this motor
	stopMotor (port10);// stop this motor
}
}
