#pragma config(StandardModel, "GTT Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{startMotor(port2,-20); /*start the motor that is connected to port 10 */
	wait(2); /*wait for 2 sec. */
	stopMotor (port2); /*stop the program*/

}
